name: apollo
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - absl-py=0.9.0=py36_0
  - astor=0.8.0=py36_0
  - astroid=2.3.3=py36_0
  - backports=1.0=py_2
  - backports.tempfile=1.0=py_0
  - backports.weakref=1.0.post1=py36h9f0ad1d_1001
  - beautifulsoup4=4.9.0=py36_0
  - blas=1.0=mkl
  - blinker=1.4=py36_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cachetools=3.1.1=py_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.14.0=py36h7a1dbc1_0
  - chardet=3.0.4=py36_1003
  - click=7.1.2=py_0
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py36h7a1dbc1_0
  - cycler=0.10.0=py36h009560c_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.2=py36_0
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py36h351948d_0
  - h5py=2.10.0=py36h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.9=py_1
  - intel-openmp=2020.1=216
  - isort=4.3.21=py36_0
  - jpeg=9b=hb83a4c4_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py36h74a9793_0
  - lazy-object-proxy=1.4.3=py36he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.11.4=h7bd577a_0
  - markdown=3.1.1=py36_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h64f37c6_0
  - mccabe=0.6.1=py36_1
  - mkl=2020.1=216
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.15=py36h14836fe_0
  - mkl_random=1.1.1=py36h47e9c7a_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.3=py36h47e9c7a_0
  - pip=20.0.2=py36_3
  - protobuf=3.11.4=py36h33f27b4_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyjwt=1.7.1=py36_0
  - pylint=2.4.4=py36_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h6538335_2
  - pyreadline=2.1=py36_1
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h9f7ef89_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.23.0=py36_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scipy=1.4.1=py36h9439919_0
  - setuptools=46.4.0=py36_0
  - sip=4.19.8=py36h6538335_0
  - soupsieve=2.0.1=py_0
  - sqlite=3.31.1=h2a8f88b_1
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=eigen_py36hdbbabfe_0
  - tensorflow-base=2.1.0=eigen_py36h49b2757_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - termcolor=1.1.0=py36_1
  - tornado=6.0.4=py36he774522_1
  - typed-ast=1.4.1=py36he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - wheel=0.34.2=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - wrapt=1.12.1=py36he774522_1
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - cssselect==1.1.0
    - dataclasses==0.7
    - filelock==3.0.12
    - flask==1.1.2
    - flask-wtf==0.14.3
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - joblib==0.15.1
    - jsonify==0.5
    - lxml==4.5.1
    - markupsafe==1.1.1
    - namegenerator==1.0.6
    - numpy==1.18.4
    - regex==2020.5.14
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - six==1.15.0
    - tokenizers==0.7.0
    - tqdm==4.46.0
    - transformers==2.10.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wtforms==2.3.1

